name: Image Builder

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Docker Build Directory
        uses: actions/checkout@master
        with:
          repository: phosae/pause
          path: ./build
      - name: make arch dir
        run: |
          mkdir ./build/amd64 && mkdir ./build/arm64
      - name: Put version to env
        run: |
          echo "VERSION=$(cat ./build/VERSION)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: zengxu
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push minimal version
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./build
          build-args: |
            VERSION=${{ env.VERSION }}
          # Note: tags has to be all lower-case
          tags: |
            zengxu/pause:${{ env.VERSION }}
          platforms: |
            linux/amd64,linux/arm64
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

